import { SlCourseTemplate } from '@/features/courses/slCourseModel';

export type MaritimeTrack =
  | 'officer_cadet'
  | 'rating_pre_sea'
  | 'stcw_mandatory'
  | 'stcw_advanced'
  | 'simulator'
  | 'competency_cop'
  | 'maritime_english'
  | 'short_refresher';

export type MaritimeTrackInfo = {
  id: MaritimeTrack;
  label: string;
  subtitle: string;
};

export const MARITIME_TRACKS: MaritimeTrackInfo[] = [
  { id: 'officer_cadet', label: 'Officer cadet', subtitle: 'Deck / engine / ETO multi-phase' },
  { id: 'rating_pre_sea', label: 'Rating & pre-sea', subtitle: 'Deck, engine, ETO ratings' },
  { id: 'stcw_mandatory', label: 'STCW mandatory', subtitle: 'PST, PSSR, FA, FF, SSA' },
  { id: 'stcw_advanced', label: 'STCW advanced', subtitle: 'AFF, PSC&RB, medical, revalidation' },
  { id: 'simulator', label: 'Simulator', subtitle: 'Bridge & engine room, BRM/ERM' },
  { id: 'competency_cop', label: 'Competency / CoP', subtitle: 'OOW, engineering watch, able seafarer' },
  { id: 'maritime_english', label: 'Maritime English', subtitle: 'Operational & management level' },
  { id: 'short_refresher', label: 'Short & refresher', subtitle: 'Tanker, gas, CoC upgrade' },
];

export type MaritimeCourseTemplate = SlCourseTemplate & {
  maritimeTrack: MaritimeTrack;
  phaseLabel?: string;
  durationNote?: string;
};

export const MARITIME_COURSE_TEMPLATES: MaritimeCourseTemplate[] = [
  {
    id: 'mar-nav-cadet-p1',
    label: 'Navigation Officer Cadet — Phase I',
    sector: 'maritime',
    qualificationLevel: 'module',
    maritimeTrack: 'officer_cadet',
    phaseLabel: 'Phase I',
    durationNote: '~10–12 months shore',
    subject: 'Navigation Officer Cadet — Phase I',
    sessionType: 'simulator',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 450000,
    intakeLabel: '2026 Intake',
  },
  {
    id: 'mar-nav-cadet-p3',
    label: 'Navigation Officer Cadet — Phase III (Sea)',
    sector: 'maritime',
    qualificationLevel: 'module',
    maritimeTrack: 'officer_cadet',
    phaseLabel: 'Phase III',
    durationNote: '~12 months at sea',
    subject: 'Navigation Officer Cadet — Phase III (Sea)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 0,
  },
  {
    id: 'mar-eng-cadet-p1',
    label: 'Engineering Officer Cadet — Phase I',
    sector: 'maritime',
    qualificationLevel: 'module',
    maritimeTrack: 'officer_cadet',
    phaseLabel: 'Phase I',
    durationNote: '~10 months on campus',
    subject: 'Engineering Officer Cadet — Phase I',
    sessionType: 'lab',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 420000,
    intakeLabel: '2026 Intake',
  },
  {
    id: 'mar-eng-cadet-p2',
    label: 'Engineering Officer Cadet — Phase II (Industrial)',
    sector: 'maritime',
    qualificationLevel: 'module',
    maritimeTrack: 'officer_cadet',
    phaseLabel: 'Phase II',
    durationNote: '~9–10 months industrial',
    subject: 'Engineering Officer Cadet — Phase II (Industrial)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 0,
  },
  {
    id: 'mar-eng-cadet-p4',
    label: 'Engineering Officer Cadet — Phase IV',
    sector: 'maritime',
    qualificationLevel: 'module',
    maritimeTrack: 'officer_cadet',
    phaseLabel: 'Phase IV',
    durationNote: '~4–5 months Class III prep',
    subject: 'Engineering Officer Cadet — Phase IV',
    sessionType: 'simulator',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 150000,
  },
  {
    id: 'mar-eto-cadet-p1',
    label: 'Electro-Technical Officer Cadet — Phase I',
    sector: 'maritime',
    qualificationLevel: 'module',
    maritimeTrack: 'officer_cadet',
    subject: 'Electro-Technical Officer Cadet — Phase I',
    sessionType: 'lab',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 380000,
    intakeLabel: '2026 Intake',
  },
  {
    id: 'mar-presea-deck-rating',
    label: 'Pre-Sea Training — Deck Rating',
    sector: 'maritime',
    qualificationLevel: 'certificate',
    maritimeTrack: 'rating_pre_sea',
    subject: 'Pre-Sea Training — Deck Rating',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 11,
    suggestedFee: 95000,
    intakeLabel: '2026 Intake',
  },
  {
    id: 'mar-presea-engine-rating',
    label: 'Pre-Sea Training — Engine Rating (Motorman)',
    sector: 'maritime',
    qualificationLevel: 'certificate',
    maritimeTrack: 'rating_pre_sea',
    subject: 'Pre-Sea Training — Engine Rating (Motorman)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 11,
    suggestedFee: 95000,
    intakeLabel: '2026 Intake',
  },
  {
    id: 'mar-cop-able-deck',
    label: 'Preparatory Able Seafarer — Deck (CoP)',
    sector: 'maritime',
    qualificationLevel: 'professional',
    maritimeTrack: 'competency_cop',
    subject: 'Preparatory Able Seafarer — Deck (CoP)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 85000,
  },
  {
    id: 'mar-nav-oow-prep',
    label: 'Preparatory OOW Navigational Watch (500GT+)',
    sector: 'maritime',
    qualificationLevel: 'professional',
    maritimeTrack: 'competency_cop',
    subject: 'Preparatory OOW Navigational Watch (500GT+)',
    sessionType: 'simulator',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 180000,
  },
  {
    id: 'mar-stcw-pst',
    label: 'STCW Personal Survival Techniques (PST)',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'stcw_mandatory',
    subject: 'STCW Personal Survival Techniques (PST)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 25000,
  },
  {
    id: 'mar-stcw-pssr',
    label: 'STCW Personal Safety & Social Responsibility',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'stcw_mandatory',
    subject: 'STCW Personal Safety & Social Responsibility',
    sessionType: 'theory',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 15000,
  },
  {
    id: 'mar-stcw-fa',
    label: 'STCW Elementary First Aid',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'stcw_mandatory',
    subject: 'STCW Elementary First Aid',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 18000,
  },
  {
    id: 'mar-stcw-ff',
    label: 'STCW Fire Prevention & Fire Fighting',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'stcw_mandatory',
    subject: 'STCW Fire Prevention & Fire Fighting',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 22000,
  },
  {
    id: 'mar-stcw-basic-bundle',
    label: 'STCW Basic Safety Training (full package)',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'stcw_mandatory',
    subject: 'STCW Basic Safety Training (full package)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 85000,
  },
  {
    id: 'mar-stcw-aff',
    label: 'STCW Advanced Fire Fighting (AFF)',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'stcw_advanced',
    subject: 'STCW Advanced Fire Fighting (AFF)',
    sessionType: 'practical',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 45000,
  },
  {
    id: 'mar-brm-mgmt',
    label: 'Bridge Resource Management — Management Level',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'simulator',
    subject: 'Bridge Resource Management — Management Level',
    sessionType: 'simulator',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 65000,
  },
  {
    id: 'mar-erm-sim-op',
    label: 'Engine Room Simulator — Operational Level',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'simulator',
    subject: 'Engine Room Simulator — Operational Level',
    sessionType: 'simulator',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 55000,
  },
  {
    id: 'mar-english-op',
    label: 'Maritime English — Operational Level',
    sector: 'maritime',
    qualificationLevel: 'certificate',
    maritimeTrack: 'maritime_english',
    subject: 'Maritime English — Operational Level',
    sessionType: 'theory',
    medium: 'English',
    gradeCompat: 12,
    suggestedFee: 28000,
  },
  {
    id: 'mar-tanker-oil-chem',
    label: 'Basic Training — Oil & Chemical Tanker',
    sector: 'maritime',
    qualificationLevel: 'short_course',
    maritimeTrack: 'short_refresher',
    subject: 'Basic Training — Oil & Chemical Tanker',
    sessionType: 'theory',
    medium: 'English',
    gradeCompat: 13,
    suggestedFee: 42000,
  },
];

export function getMaritimeTemplatesForTrack(track: MaritimeTrack) {
  return MARITIME_COURSE_TEMPLATES.filter((item) => item.maritimeTrack === track);
}
